services:
  windows:
    image: dockurr/windows
    container_name: windows10
    restart: unless-stopped
    privileged: true

    environment:
      VERSION: "10"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "64G"
      BOOT: "cd"
      GPU: "virtio"
      ACCEL: "kvm"
      NETWORK: "user"
      PORT_FORWARD: "8006:8006"
      USERNAME: ${WINDOWS_USERNAME}
      PASSWORD: ${WINDOWS_PASSWORD}
      VNC: "true"
      VNC_PORT: "5900"
      RDP: "true"
      RDP_PORT: "3389"
      WEBSOCKIFY: "true"
      WEBSOCKIFY_PORT: "6080"

    ports:
      - "8006:8006"

    volumes:
      - ./data:/data
