services:
  windows:
    image: dockurr/windows
    container_name: windows10
    restart: unless-stopped
    privileged: true

    environment:
      # --- General Config ---
      VERSION: "win10"             # win11 / win10 / win7 / winxp / ...
      RAM_SIZE: "4G"               # Dung lượng RAM VM
      CPU_CORES: "2"               # Số core CPU
      DISK_SIZE: "64G"             # Dung lượng ổ đĩa chính
      DISK_TYPE: "qcow2"           # qcow2/raw
      DISK_PATH: "/data/system.qcow2"

      # --- Boot & ISO ---
      BOOT: "cd"                   # disk / cd / ...
      CDROM_URL: ""                # Link ISO gắn CD-ROM
      FLOPPY_URL: ""               # Link floppy image
      FLOPPY_DRIVE: ""             # Mount floppy
      KERNEL: ""                   # Dùng kernel custom
      INITRD: ""                   # Init RAM Disk
      APPEND: ""                   # Kernel args

      # --- GPU / Hardware ---
      GPU: "virtio"                # virtio / qxl / cirrus / none
      SOUND: "true"                # true / false
      USB: "true"                  # Bật USB device
      ACCEL: "kvm"                 # kvm / tcg (no-accel)

      # --- Network ---
      NETWORK: "user"              # user / bridge / none
      MAC_ADDRESS: ""              # Custom MAC
      PORT_FORWARD: "3389:3389"    # Forward port
      QEMU_NET_OPTS: ""

      # --- Credentials ---
      USERNAME: ${WINDOWS_USERNAME}
      PASSWORD: ${WINDOWS_PASSWORD}

      # --- Advanced ---
      VNC: "true"                  # true = mở VNC server
      VNC_PORT: "5900"
      SPICE: "false"
      RDP: "true"
      RDP_PORT: "3389"
      SSH: "false"
      WEBSOCKIFY: "true"           # Web-based VNC proxy
      WEBSOCKIFY_PORT: "6080"

      QEMU_DISPLAY: "gtk"          # gtk / sdl / none
      EXTRA_ARGS: ""               # custom qemu args

      # --- Disks & Storage ---
      DISK2_SIZE: ""               # Ổ phụ
      DISK2_PATH: ""
      DISK3_SIZE: ""
      DISK3_PATH: ""
      CDROM: ""                    # ISO cài đặt
      DRIVE_OPTS: ""               # Tùy chỉnh drive

      # --- Debug ---
      DEBUG: "false"
      LOG_LEVEL: "info"

    ports:
      - "8006:8006"   # noVNC web
      - "3389:3389"   # RDP
      - "5900:5900"   # VNC
      - "6080:6080"   # Websockify

    volumes:
      - ./data:/data